-- Battlestation Supabase Schema — ISOLATED STACK
-- Run this in YOUR OWN Supabase project (Dashboard → SQL Editor → paste → Run).
-- Order matters: working_sessions first (FK deps from session_locks / ai_capacity_ledger).
-- After running, put your project URL + anon key in .env (SUPA_URL / SUPA_KEY).

-- ============================================================================
-- working_sessions
-- Groups multiple 5-hour Claude Code sessions into a single logical "sitting".
-- ID format: WS-YYMMDD-seq (e.g., WS-260407-1)
-- RESERVED: no writer ships in this pack yet — session_locks/session_tasks
-- reference it (parent "sitting"), but populating it is left to the operator
-- (e.g. a /start-sitting flow). Kept so the FKs resolve.
-- ============================================================================
CREATE TABLE IF NOT EXISTS working_sessions (
  id                text        PRIMARY KEY,             -- WS-YYMMDD-seq format
  started_at        timestamptz NOT NULL DEFAULT now(),
  ended_at          timestamptz,
  account_sequence  text[]      NOT NULL DEFAULT '{}',   -- accounts used during sitting (A, B, C)
  tools_used        text[]      NOT NULL DEFAULT '{}',   -- tools invoked (claude-code, codex, cursor, etc.)
  directive         text,                                -- human-readable goal for the sitting
  tasks_completed   text[]      DEFAULT '{}',            -- refs of tasks completed
  summary           text,                                -- end-of-session summary
  status            text        NOT NULL DEFAULT 'active' -- active | done
);

-- ============================================================================
-- session_locks
-- Tracks every active Claude Code / Codex session for coordination.
-- The heartbeat_at column is bumped every ~5 min; stale sessions are expired
-- by the expire-sessions cron job (heartbeat_at > 30 min ago).
-- ============================================================================
CREATE TABLE IF NOT EXISTS session_locks (
  id                uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id        text        NOT NULL,                -- cc-$PPID or codex-$ID
  tool              text        NOT NULL,                -- claude-code | codex | cursor
  repo              text        NOT NULL,                -- repository name
  task_ref          text        NOT NULL,                -- Notion task page ID or slug
  task_name         text        NOT NULL,                -- human-readable task name
  files_touched     text[],                              -- files this session owns (conflict detection)
  status            text        NOT NULL DEFAULT 'active', -- active | done
  claimed_at        timestamptz DEFAULT now(),
  heartbeat_at      timestamptz DEFAULT now(),
  released_at       timestamptz,
  commit_sha        text,                                -- final commit SHA on completion
  notes             text,
  account           text        NOT NULL DEFAULT 'A',    -- which Claude account (A, B, C)
  working_session   text        REFERENCES working_sessions(id) -- parent sitting
);

-- ============================================================================
-- session_tasks
-- Per-task log within a session. Tracks individual units of work, their
-- status, and any artifacts produced (PRs, files, screenshots, etc.).
-- ============================================================================
CREATE TABLE IF NOT EXISTS session_tasks (
  id                bigint      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  session_id        text        NOT NULL,                -- cc-$PPID
  working_session   text,                                -- parent WS-* ID
  task_name         text        NOT NULL,
  task_ref          text,                                -- Notion page ID or slug
  project           text,                                -- atlas | paperclip | kaa | etc.
  status            text        NOT NULL DEFAULT 'active', -- active | done | blocked
  started_at        timestamptz NOT NULL DEFAULT now(),
  completed_at      timestamptz,
  artifacts         jsonb       DEFAULT '{}',            -- {pr_url, commit_sha, files, screenshots}
  notes             text,
  created_at        timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- account_capacity
-- Snapshot of rate-limit usage per Claude account. Updated by the
-- capacity-snapshot cron job. One row per account (A, B, C).
-- ============================================================================
CREATE TABLE IF NOT EXISTS account_capacity (
  account           text        PRIMARY KEY,             -- A, B, or C
  account_name      text,                                -- human-readable (e.g., "KAA (Builder)")
  five_hour_used_pct  numeric,                           -- 0-100 rolling 5h window usage
  five_hour_resets_at bigint,                            -- epoch seconds when 5h window resets
  seven_day_used_pct  numeric,                           -- 0-100 rolling 7-day window usage
  seven_day_resets_at bigint,                            -- epoch seconds when 7-day window resets
  snapshot_at       timestamptz DEFAULT now(),            -- when this snapshot was taken
  is_active         boolean     DEFAULT false             -- whether this is the currently active account
);

-- ============================================================================
-- ai_capacity_ledger
-- Logs every AI platform usage event across all tools (Claude, Codex, Gemini,
-- Grok, etc.). Used for cost tracking and capacity planning.
-- ============================================================================
CREATE TABLE IF NOT EXISTS ai_capacity_ledger (
  id                uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  platform          text        NOT NULL,                -- claude | codex | gemini | grok
  task_id           text        NOT NULL,                -- Notion task ref or free-form ID
  session_type      text        NOT NULL,                -- chat | build | search | plan
  started_at        timestamptz NOT NULL DEFAULT now(),
  ended_at          timestamptz,
  duration_seconds  integer,
  tokens_in         integer,                             -- input tokens consumed
  tokens_out        integer,                             -- output tokens generated
  estimated_cost    numeric,                             -- USD estimated cost
  outcome           text,                                -- success | partial | failed
  notes             text,
  created_at        timestamptz DEFAULT now(),
  account           text        NOT NULL DEFAULT 'A',    -- which Claude account (A, B, C)
  working_session   text        REFERENCES working_sessions(id) -- parent sitting
);

-- ============================================================================
-- account_capacity_history
-- Time-series audit log of account capacity snapshots. Append-only.
-- Populated by: capacity-snapshot cron (every 5min), account switch departure.
-- ============================================================================
CREATE TABLE IF NOT EXISTS account_capacity_history (
  id                bigserial   PRIMARY KEY,
  account           text        NOT NULL,                -- A, B, or C
  five_hour_used_pct real,                               -- 5h window usage %
  seven_day_used_pct real,                               -- 7-day rolling usage %
  is_active         boolean     DEFAULT false,           -- was this account active at snapshot time?
  source            text        DEFAULT 'cron',          -- cron | switch_departure | manual
  snapshot_at       timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ach_account_time
  ON account_capacity_history(account, snapshot_at DESC);

-- ============================================================================
-- session_messages  (Wire — inter-session messaging)
-- Written by lib/wire.sh, read+expired by the wire daemon / hooks.
-- ============================================================================
CREATE TABLE IF NOT EXISTS session_messages (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  from_session  text        NOT NULL,                 -- cc-$PPID of sender
  to_session    text        NOT NULL,                 -- cc-$PPID of recipient ('*' = broadcast)
  msg_type      text        NOT NULL,                 -- question|ack|info|status|file_release|patch|task_claim|task_handoff
  payload       jsonb       NOT NULL DEFAULT '{}',    -- type-specific body
  cycle_id      text,                                 -- optional grouping
  read          boolean     NOT NULL DEFAULT false,
  acked         boolean     NOT NULL DEFAULT false,
  created_at    timestamptz NOT NULL DEFAULT now(),
  expires_at    timestamptz NOT NULL DEFAULT now() + interval '30 minutes'
);
CREATE INDEX IF NOT EXISTS idx_sm_inbox ON session_messages(to_session, read, created_at);
CREATE INDEX IF NOT EXISTS idx_sm_expiry ON session_messages(expires_at);

-- ============================================================================
-- build_ledger  (everything shipped — commits, decisions, ideas, audit findings)
-- Written by hooks/build-ledger.sh on every git commit.
-- ============================================================================
CREATE TABLE IF NOT EXISTS build_ledger (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id      text,
  project         text,
  company         text,
  item_type       text        NOT NULL DEFAULT 'build', -- build|decision|idea|audit_finding|...
  title           text        NOT NULL,
  files           jsonb       DEFAULT '[]',
  commit_sha      text,
  test_status     text        DEFAULT 'untested',       -- untested|pass|fail
  test_hint       text,
  source          text        DEFAULT 'commit',          -- commit|manual|...
  difficulty      text,
  points          integer     DEFAULT 0,
  cycle_id        text,
  finding_code    text,                                  -- e.g. WARN-2 (audit findings)
  finding_status  text,                                  -- open|closed
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_bl_project_time ON build_ledger(project, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bl_finding ON build_ledger(project, finding_code, item_type);
